server:
  port: 9000
spring:
  application:
    name: dsp-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

zuul:
  prefix: /bigdata
  routes:
    sponsor:
      path: /dsp-sponsor/**
      serviceId: eureka-client-dsp-sponsor
      strip-prefix: false



