server:
  port: 7001
  servlet:
    context-path: /dsp-search

spring:
  application:
    name: eureka-client-dsp-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dsp_data?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: Djangobbs
    binlogName: binlog.000038
    position: 60451

  kafka:
    topic: ad-search-mysql-data
